name: ♻️ Sync Labels

on:
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-20.04
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3

      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync-action@v1
        with:
          token: ${{ secrets.LABEL_SYNC_GITHUB_PAT }}
          config-file: .github/labels.yml
          clean-labels: true
